from __future__ import annotations
from abc import ABC, abstractmethod
from typing import List, Optional
from todolist.models.project import Project as ProjectModel
from todolist.models.task import Task as TaskModel

class ProjectRepositoryInterface(ABC):
    @abstractmethod
    def add(self, project: ProjectModel) -> ProjectModel: ...
    @abstractmethod
    def get(self, project_id: int) -> Optional[ProjectModel]: ...
    @abstractmethod
    def list(self) -> List[ProjectModel]: ...
    @abstractmethod
    def delete(self, project_id: int) -> bool: ...
    @abstractmethod
    def find_by_name(self, name: str) -> Optional[ProjectModel]: ...

class TaskRepositoryInterface(ABC):
    @abstractmethod
    def add(self, task: TaskModel) -> TaskModel: ...
    @abstractmethod
    def get(self, task_id: int) -> Optional[TaskModel]: ...
    @abstractmethod
    def list_by_project(self, project_id: int) -> List[TaskModel]: ...
    @abstractmethod
    def delete(self, task_id: int) -> bool: ...
    @abstractmethod
    def update(self, task: TaskModel) -> TaskModel: ...
    @abstractmethod
    def list_overdue(self) -> List[TaskModel]: ...